Added the operation protobuf.
AquaticInformatics/ONE.Interfaces.ProtocolBuffers pull request #37
Opened 2023-06-16 15:59 UTC by ColeGlaserAQI

2023-06-16 17:50 UTC, AQI-DanG requested changes
Probably need a plural and definitely need to add it to content

2023-06-16 18:08 UTC, AQI-DanG approved these changes

2023-06-16 18:08 UTC, AQI-DanG approved these changes

2023-06-20 19:33 UTC, KentMiller approved these changes

2023-06-20 20:48 UTC, joezhou-aqi approved these changes

2023-06-26 16:27 UTC, KentMiller approved these changes

2023-06-27 15:41 UTC, joezhou-aqi approved these changes

2023-06-27 15:49 UTC, merged

2023-06-28 13:47 UTC, AQI-DanG commented on proto/one/common/core/content.proto
> +import "operation.proto";
Since you changed this to operation_export I don't think this import is going to work and will prevent building the protobufs